### ISSUE TITLE
TypeError: htmlspecialchars

### ISSUE THREAD

**Issue by dragonauta** [apazureck/dokuwiki-chordsheets#1]
Hi.
I'm trying to use the plugin in my Dokuwiki. After installing and enabling the plugin (using the Extension Manager) I go to my page and add <chordSheet> tags. Actually I copy&paste the example of README.

I get then this error:

> TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given
> 
> An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the chordsheets plugin.
> 
> More info has been written to the DokuWiki error log.

My system is:
DokuWiki 2023-04-04a "Jack Jackrum"
Debian Bookworm 12.1
PHP 8.2.7
Apache2 2.4.57

The log (through Dokuwiki interface) shows this:

> 2023-11-09 19:12:43TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given/var/www/html/doku/inc/common.php(29)
>     #0 /var/www/html/doku/inc/common.php(29): htmlspecialchars()
>     #1 /var/www/html/doku/inc/parser/xhtml.php(1688): hsc()
>     #2 /var/www/html/doku/lib/plugins/chordsheets/syntax.php(64): Doku_Renderer_xhtml->_xmlEntities()
>     #3 /var/www/html/doku/inc/parser/renderer.php(119): syntax_plugin_chordsheets->render()
>     #4 /var/www/html/doku/inc/parserutils.php(700): Doku_Renderer->plugin()
>     #5 /var/www/html/doku/inc/parserutils.php(158): p_render()
>     #6 /var/www/html/doku/inc/parserutils.php(96): p_cached_output()
>     #7 /var/www/html/doku/inc/Ui/PageView.php(68): p_wiki_xhtml()
>     #8 /var/www/html/doku/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
>     #9 /var/www/html/doku/inc/template.php(100): dokuwiki\Action\Show->tplContent()
>     #10 [internal function]: tpl_content_core()
>     #11 /var/www/html/doku/inc/Extension/Event.php(133): call_user_func_array()
>     #12 /var/www/html/doku/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
>     #13 /var/www/html/doku/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
>     #14 /var/www/html/doku/lib/tpl/dokuwiki/main.php(59): tpl_content()
>     #15 /var/www/html/doku/inc/actions.php(27): include('...')
>     #16 /var/www/html/doku/doku.php(126): act_dispatch()
>     #17 {main}

Is there any other info I can provide?
Thanks!

**Comment by beemeeup** [comment]
Same Error on my Site

**Comment by apazureck** [comment]
Hi,

Sorry for the late reply. I did not notice this last year. I hope I have time around Christmas, but for now I am too busy. I am currently not using the plugin myself, as my band chose not to use the wiki anymore, but I see what I can do. Should not be impossible to fix. Maybe something changed in newer wiki versions.

**Comment by dragonauta** [comment]
Thanks @apazureck .
Don't worry, take your time.
I would love to use the chord plugin in my songs because it looks awesome.
For now I just put the "CDEFGAB" notation over the lyrics. :)

**Comment by Antiokh** [comment]
> Hi,
> 
> Sorry for the late reply. I did not notice this last year. I hope I have time around Christmas, but for now I am too busy. I am currently not using the plugin myself, as my band chose not to use the wiki anymore, but I see what I can do. Should not be impossible to fix. Maybe something changed in newer wiki versions.

I'm also interested in your plugin, the idea is awesome. Where did you switch with your band?

**Comment by Lord-Dimwit-Flathead-the-Excessive** [comment]
Also interested in your plug-in and having same issue:
![Image](https://github.com/user-attachments/assets/8256eaea-12e4-4da7-9fa4-ce477c284338)

Debian 12.8
PHP 8.2.28
Apache 2.4.62

**Comment by apazureck** [comment]
Closed, fixed in 0.1.2
